# -*- coding: utf-8 -*-
"""PDF_Prueba2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfb4F8v3Id9chq_ilsxX_fdxz8SgFgMD
"""

!apt-get install poppler-utils tesseract-ocr-spa

pip install pdf2image pytesseract PyPDF2

import os
import pandas as pd
from pdf2image import convert_from_path
import pytesseract  # Import pytesseract
from google.colab import drive

drive.mount('/content/drive')

import os
from pdf2image import convert_from_path
import pytesseract  # Import pytesseract

# Set the folder path where the PDF files are located
pdf_folder = '/content/drive/MyDrive/PDFS/IMSS/'

# Set the characters between which the strings should be extracted
start_char = '09 53 '
end_char = '/2024'

# Initialize an empty list to store the extracted strings
extracted_strings = []

# Loop through all PDF files in the folder
for filename in os.listdir(pdf_folder):
    if filename.endswith('.pdf'):
        # Convert the PDF file to images
        pdf_path = os.path.join(pdf_folder, filename)
        images = convert_from_path(pdf_path)

        # Loop through each image and extract text using pytesseract
        for img in images:
            text = pytesseract.image_to_string(img)  # Use pytesseract
            start_indices = [i for i, char in enumerate(text) if char == start_char]
            end_indices = [i for i, char in enumerate(text) if char == end_char]

            for start, end in zip(start_indices, end_indices):
                if end > start:
                    extracted_string = text[start+1:end]
                    extracted_strings.append(extracted_string)

# Create a pandas DataFrame from the extracted strings
df = pd.DataFrame({'Extracted Strings': extracted_strings})

# Save the DataFrame to an Excel file
excel_file = '/content/drive/MyDrive/PDFS/IMSS/file_example.xlsx'
df.to_excel(excel_file, index=False)

# Print a success message
print(f"Extracted strings from PDF files and saved to {excel_file}")